# Generated by Django 5.1.1 on 2026-03-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veduci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Vedúci',
                'verbose_name_plural': 'Vedúci',
            },
        ),
        migrations.CreateModel(
            name='Kruzok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('den', models.CharField(max_length=20)),
                ('miestnost', models.CharField(max_length=50)),
                ('veduci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kruzky.veduci')),
            ],
            options={
                'verbose_name': 'Krúžok',
                'verbose_name_plural': 'Krúžky',
            },
        ),
    ]
